### ISSUE TITLE
Considerable drop in tracker thread frame rate 

### ISSUE THREAD

**Issue by AndreasRef** [HalfdanJ/ofxFaceTracker2#10]
Hi @HalfdanJ 

Really great work with this addon, thanks a lot for putting it out! 

I experience a considerable drop in tracker thread frame rate when running the examples. 
Frame rate typically starts out around 20-30 but drops to 4-10 fps within a few minutes. Most of the time this still gives acceptable performance, but sometimes the tracking is too slow to use for real time applications. 

When using an external webcam (Logitech 925c) the tracker thread frame rate often drop as low as 2 or 3 fps, and I experience is a lack of a few seconds on the tracker as well as the video output. 

Anybody else experiencing similar issues? Or do you have any ideas how to avoid / work around these?

I am running the examples in release mode on a somewhat powerful 2013 MacBook Pro (16 GB DDR3, 2.3 GHz Intel Core i7).

Cheers
Andreas fra København

**Comment by HalfdanJ** [comment]
Hej Andreas

Are you running the code in Release mode? There is a huge difference running the code optimized. The numbers you mention don't sound correct, so if you do run them in release mode, then there might be something wrong in the code, on my computer (with similar specs and built-in webcam) it runs at 30-40 fps.

**Comment by AndreasRef** [comment]
Yes, I am running in Release mode...

I am just running the examples, have not altered any of the code.

Running of_v0.9.0 by the way.

**Comment by HalfdanJ** [comment]
Is dlib complaining in the console? 
Is the apps foreground thread running 60fps?

**Comment by HalfdanJ** [comment]
I've just tried to roll back to 0.9.0 release with no affect, still runs fast here, and I've previously tested on machines that where older than yours still running without problems (mbp 2011).  

To get a better idea, then please try and run a profiler on the code and see if its the dlib code that is slow or if its some pixel conversion / downscaling that is running slowly.

**Comment by AndreasRef** [comment]
No complains in the console. 

The foreground thread normally runs 60fps. On one occasion I have have seen it drop down somewhere between 40-50 when the tracker thread frame was 2-3 fps.

**Comment by AndreasRef** [comment]
Sure. Could you give me a small hint/link as to how to perform this and what to look for? I have never run a profiler before.

**Comment by HalfdanJ** [comment]
Run the profiler from xcode `Product -> Profile` and choose Time Profiler and press run. 

After you have had the app running, stop it. You can save the output and send it to me. I can recommend to invert the call tree, it makes it easier for this type of stuff to see what end functions are taking up the time.

![image](https://cloud.githubusercontent.com/assets/227529/17860016/d9c04c56-6859-11e6-8bbe-dc1d0c0b06e4.png)


 If you double click on a row it will take you to the code that is calling the function, the trick is to find the functions in the background thread of the ofxFacetracker2, and find what lines take up the most time.

**Comment by AndreasRef** [comment]
Great thanks! I ran it and have sent the output to your mail.

**Comment by HalfdanJ** [comment]
Hmmm, looks very similar to mine.... Do you see any memory leaks / issues? (You can add a memory instrument in instruments to measure)

**Comment by AndreasRef** [comment]
I tried adding "Leaks" from the instruments "+"-button.

It seems that I get a leak a few seconds after the program starts. 

![screen shot 2016-08-22 at 17 50 05](https://cloud.githubusercontent.com/assets/9645568/17861349/faf19bbe-6890-11e6-8476-e7a8198e36ec.png)


I ran the program three times and got the leak every time:

![screen shot 2016-08-22 at 17 53 37](https://cloud.githubusercontent.com/assets/9645568/17861439/641d79fa-6891-11e6-8fe2-1a6cf8f72592.png)

**Comment by HalfdanJ** [comment]
Thats probably not it. One leak on startup is not the problem (the gray markers says No new leaks) 
Im not really sure what else to do.

**Comment by AndreasRef** [comment]
Okay, yeah me neither... Thanks for trying to help me out though!

**Comment by AndreasRef** [comment]
The problem has more or less disappeared on my mac, so perhaps it was a local thing. Closing down the issue.
