### ISSUE TITLE
Difference getImageMesh() between ofxFaceTracker and ofxFaceTracker2

### ISSUE THREAD

**Issue by nnn112358** [HalfdanJ/ofxFaceTracker2#25]
I want to make things like FaceSubstitution by ofxFaceTracker2, and I refer to https://github.com/HalfdanJ/ofxFaceTracker2/issues/9.

Looking at this, ofxFaceTracker2's  getImageMesh() is implemented.
Replacing ofxFaceTracker's getImageMesh and ofxFaceTracker2's in the  [FaceSubstitution](https://github.com/arturoc/FaceSubstitution) ,  did not work.
It seems the contents are different from those of ofxFaceTracker and ofxFaceTracker2.
I tried it with the following code.

```
ofxFaceTracker traker;
ofMesh mesh = tracker.getImageMesh();
mesh.save("traker.mesh");

ofxFaceTracker2 traker2;
ofxFaceTracker2Instance instance = traker2.getInstances()[0];
ofMesh instance.getLandmarks().getImageMesh();
mesh.save("traker2.mesh");
```

traker.mesh by ofxFaceTracker getImageMesh() is
```
ply
format ascii 1.0
element vertex 66
property float x
property float y
property float z
property float u
property float v
element face 91
property list uchar int vertex_indices
end_header
229.188 248.479 0 229.188 248.479
230.094 275.276 0 230.094 275.276
...
...

```
traker2.mesh by ofxFaceTracker2 getImageMesh() is

```
ply
format ascii 1.0
element vertex 333
property float x
property float y
property float z
element face 111
property list uchar int vertex_indices
end_header
359 261 0
353 220 0
...
...

```

I would be pleased if you give me advice！

**Comment by ThomasColliers** [comment]
I gave this a quick shot today. Using the mesh directly from getImageMesh is not possible because due to the triangulation, you can't just map the coordinates from one mesh to the uv's of another as the topology is probably different.

A quick and dirty solution that works for me but is a bit jittery when the topology changes:

- Get the source coordinates, this is a good list of UV coordinates for each point of the face.
```cpp
source_coordinates = source_face.getLandmarks().getImagePoints();`
```
- Build a map of all target coordinates pointing to the point index
```cpp
std::vector<ofVec2f> points = target_face.getLandmarks().getImagePoints();
std::unordered_map<Coord, int> index_map;
int index = 0;
for(std::vector<ofVec2f>::iterator it = points.begin(); it != points.end(); ++it){
    Coord c = {(int)it->x,(int)it->y};
    index_map[c] = index;
    ++index;
}
``` 
- Get the mesh of our target and for each vertex, look up in our map what the texture coord should be
```cpp
ofMesh mesh = target_face.getLandmarks().getImageMesh();
std::vector<ofVec3f> vertices = mesh.getVertices();
for(std::vector<ofVec3f>::iterator it = vertices.begin(); it != vertices.end(); ++it){
    Coord c = {(int)it->x,(int)it->y};
    std::unordered_map<Coord, int>::iterator i = index_map.find(c);
    assert(i != index_map.end());
    mesh.addTexCoord(source_coordinates[i->second]);
}
```

A better solution would be to use a fixed topology for the mesh and then just adjust the vertices of the mesh. That would be much faster and less jittery. I'll try to work this out to share an example with a pull request.

**Comment by samhains** [comment]
has anyone happened to figure this out? also trying to do face substitution with ofxFaceTracker2 :D

**Comment by ThomasColliers** [comment]
Yes in the end I went for a fixed topology which was much more stable. I also added a Kalman filter to the positions to smoothen out some noise coming from the tracker.

Here's the class I used extending ofMesh:
https://gist.github.com/ThomasColliers/375c65a3afd529bd1b9f28fe48f94cd3

To use, initialize the uvs based on the source UV's:
```
source_coordinates = source_face.getLandmarks().getImagePoints();
target_mesh.update_uvs(source_coordinates);
```

And then on each camera frame update the vertex positions using:
```
target_mesh.update_vertices(target_face.getLandmarks().getImagePoints());
```

**Comment by samhains** [comment]
Hey @ThomasColliers, thanks a lot for sharing... I'm attempting to implement your code at the moment - but i'm getting this error:
```class "ofxCv::KalmanPosition_<float>" has no member "initialvals" TargetMesh.cpp	138	
'initialvals': is not a member of 'ofxCv::KalmanPosition_<float>'```

Did you modify your KalmanPosition class? I can't seem to find 'initialvals' when I search the ofxCv repository.

Thansk!

Sam

**Comment by samhains** [comment]
Amazing. Thankyou so much!  I finally got this to work... I might do a PR with my working face substitution code if you don't mind? Would have helped me a lot to have had an example.

**Comment by ThomasColliers** [comment]
Glad it worked for you. Ofcourse, I think it would be great to have this as an example so go ahead :)

**Comment by nnn112358** [comment]
Oh, this is amazing!!
I was suffering because I did not get along well.
I appreciate it.

**Comment by shiyuugohirao** [comment]
Thank you, ThomasColliers!
I could make face substitution referring to https://github.com/HalfdanJ/ofxFaceTracker2/issues/25#issuecomment-342467114
For now, this code is running on 60fps.
https://github.com/shiyuugohirao/faceSubstitution_with_ofxFaceTracker2

**Comment by xanpj** [comment]
@nondescriptpointer Thomas's links are down https://gist.github.com/ThomasColliers/375c65a3afd529bd1b9f28fe48f94cd3

Does someone still have the modified Kalman.h and Kalman.cpp available?

Thanks in advance!

**Comment by nondescriptpointer** [comment]
@xanpj here you go: https://gist.github.com/nondescriptpointer/375c65a3afd529bd1b9f28fe48f94cd3
