### ISSUE TITLE
dashes in project name

### ISSUE THREAD

**Issue by ofZach** [HalfdanJ/ofxFaceTracker2#31]
this is a small thing but I'm having some issues with dashes in the project name since java doesn't like dashes / hyphens in package names: 

ie: 

OFActivity.java 
has 
`package cc.openframeworks.example-android;`

but compiler complains about the - suggesting that a ; is needed.

**Comment by HalfdanJ** [comment]
The project generator shouldn't create that package name? I changed it a long time ago to replace hyphens https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/androidStudioProject.cpp#L18

**Comment by ofZach** [comment]
sorry I realize this might be more of an OF issue but just thought I'd mention it since I saw it with your example. 

I'm using the pg from 0.9.8, maybe the changes aren't in there?  my setup is basically as per @irealva's https://medium.com/@ire_alva/getting-started-with-openframeworks-on-android-5202b92f6582

when I just made a project using that called "simple-test" I see this in OFActivity.java which gives problems (java will complain about this package name) 

```
package cc.openframeworks.simple-test;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import cc.openframeworks.OFAndroid;
```

but the manifest looks right

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="cc.openframeworks.simpletest"
```

**Comment by HalfdanJ** [comment]
Mmm ah i know why.. Yeah this is a bug in openFrameworks PG. I had in my version of the openframeworks revamp removed the OFActivity.java file from the template (its not needed for 99% of the apps, and can very easily be added) so didnt have this bug.
