### ISSUE TITLE
Incomplete type 'ofMesh'

### ISSUE THREAD

**Issue by samhains** [HalfdanJ/ofxFaceTracker2#41]
Hey,

I've been having a lot of problems trying to get this to compile on windows. 

I downloaded the most recent nightly build  (of_v20180415_vs2017_nightly.zip). I linked my dlib library to the project to get the 'missing dlib' errors to pass. 

However I am confronted with a new problem, apparantly getImageMesh is returning an incomplete type "ofMesh".

![error](https://user-images.githubusercontent.com/7479037/38906482-f429de34-4284-11e8-98f8-a1cb1d7ac308.PNG)

No idea whats going on here! 

Thanks :)

**Comment by bakercp** [comment]
The includes situation has changed the most recent version of and ofxFaceTracker2 needs to be updated.  There are fixes in my branch, but it also has a dependency of ofxDlib, so you'd have to get that too.  https://github.com/bakercp/ofxDlib/ and https://github.com/bakercp/ofxFaceTracker2

**Comment by samhains** [comment]
thanks again @bakercp - yes I noticed this TODO... I think I might have almost figured out how to compile dlib for your library ... if I do I will post you instructions! (presuming that helps)

**Comment by bakercp** [comment]
Certainly would help.  :)  If you can add your technique to https://github.com/bakercp/ofxDlib/blob/master/scripts/formulas/dlib.sh

**Comment by samhains** [comment]
@bakercp was correct in suggesting this issue is caused by using a 'too new' version of open frameworks. I was successfully able to compile by using ofx 0.9.8, stable branch ofxCv and ofxFaceTracker2 at commit 13e95fa81b9ea38f437ad1c4121e5c5a9d1bfd1a
