### ISSUE TITLE
Project Generator is not including Dlib !!!

### ISSUE THREAD

**Issue by joaodafonseca** [HalfdanJ/ofxFaceTracker2#45]
Hi there,

I'm trying to create a project by using the project generator but looks like it's not including the libs under **libs/dlib/** folder.  Getting the following error:

**'dlib/image_processing/frontal_face_detector.h' file not found**

How can I fix it? Is it possible to add the library manually.?

Thanks in advance,
J

**Comment by joaodafonseca** [comment]
Fixed by changing Dlib paths

**Comment by AndreasRef** [comment]
Hi joaodafonseca. How specifically did you change the Dlib paths to get it working again?

Best
Andreas
