### ISSUE TITLE
How to use getImageMesh() from ofxFaceTracker2Landmarks

### ISSUE THREAD

**Issue by Javingka** [HalfdanJ/ofxFaceTracker2#9]
Hi @HalfdanJ 

Fist of all, thanks for share this code.

I want to build an example as the [FaceSubstitution](https://github.com/arturoc/FaceSubstitution). So I am starting for the very beginning:

I have the example-simple working, and my first goal is get a mesh from the face tracked. For this I think need this 2 steps:
- Get a list of points from the 68 landmarks coordinates.
- Build a mesh using that points.

[ofxFaceTracker](https://github.com/kylemcdonald/ofxFaceTracker) has a method called 'getImageMesh()' that get the points form the image and returns a mesh builded with those points.

I see in ofxFaceTracker2, that could be used 'getImageMesh()' too, but in this case I suppose I have to instantiate a ofxFaceTracker2Landmarks Object to be able to call this method on it. And I see that the constructor of this Object needs the two following parameters:

````
    ofxFaceTracker2Landmarks(dlib::full_object_detection shape, ofxFaceTracker2InputInfo & info);
````

I don't know what are those parameters ( dlib::full_object_detection, ofxFaceTracker2InputInfo & info) and how can I get such values.

Can you give me a hand, some orientation what should I do ?

Thanks!

**Comment by HalfdanJ** [comment]
Yeah, I've wanted to do the same, but didnt get time to do it. So if you do so, it would be great with a PR with the example, or at least a link so I can link to it. 

`getImageMesh()` has been implemented in ofxFaceTracker2, its found in the [ofxFaceTracker2Landmarks class](https://github.com/HalfdanJ/ofxFaceTracker2/blob/master/src/ofxFaceTracker2Landmarks.cpp#L104)

You can get the list of image points by calling 

```c++
ofxFaceTracker2Instance instance = tracker.getInstances()[0];
vector<ofVec2f>  instance.getLandmarks().getImagePoints();
```

Or the image mesh by calling 

```c++
ofxFaceTracker2Instance instance = tracker.getInstances()[0];
vector<ofVec2f>  instance.getLandmarks(). getImageMesh();
```

Hope this works for you!
